apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-api-pod-develop
  namespace: kubernetes-cluster-prasunguchhait
  labels:
    app: oneapi-develop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: oneapi-develop
  template:
    metadata:
      labels:
        app: oneapi-develop
    spec:
      containers:
      - name : oneapi-develop
        image: prasunguchhait/app-prasunguchhait:develop-latest
        ports:
          - name: http
            containerPort: 80
            protocol: TCP