apiVersion: v1
kind: Service
metadata:
  name: one-api-service-develop
  namespace: kubernetes-cluster-prasunguchhait
  labels: 
    app: one-api-service-develop
spec:
  type: NodePort
  selector:
    app: oneapi-develop
  ports:
    - protocol: TCP
      nodePort: 30158
      port: 80
      targetPort: 80