apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-api-pod-master
  namespace: kubernetes-cluster-prasunguchhait
  labels:
    app: oneapi-master
spec:
  replicas: 4
  selector:
    matchLabels:
      app: oneapi-master
  template:
    metadata:
      labels:
        app: oneapi-master
    spec:
      containers:
      - name : oneapi-master
        image: prasunguchhait/app-prasunguchhait:master-latest
        ports:
          - name: http
            containerPort: 80
            protocol: TCP